/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PaymentSetupRouteImport } from './routes/payment-setup'
import { Route as PaymentDetailsRouteImport } from './routes/payment-details'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotificationSettingsRouteImport } from './routes/notification-settings'
import { Route as NewOrderRouteImport } from './routes/new-order'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BusinessProfileRouteImport } from './routes/business-profile'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as ForgotPasswordVerifyRouteImport } from './routes/forgot-password.verify'
import { Route as ForgotPasswordResetRouteImport } from './routes/forgot-password.reset'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'

const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSetupRoute = PaymentSetupRouteImport.update({
  id: '/payment-setup',
  path: '/payment-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentDetailsRoute = PaymentDetailsRouteImport.update({
  id: '/payment-details',
  path: '/payment-details',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationSettingsRoute = NotificationSettingsRouteImport.update({
  id: '/notification-settings',
  path: '/notification-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewOrderRoute = NewOrderRouteImport.update({
  id: '/new-order',
  path: '/new-order',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessProfileRoute = BusinessProfileRouteImport.update({
  id: '/business-profile',
  path: '/business-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const ForgotPasswordVerifyRoute = ForgotPasswordVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ForgotPasswordRoute,
} as any)
const ForgotPasswordResetRoute = ForgotPasswordResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => ForgotPasswordRoute,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/$customerId',
  path: '/$customerId',
  getParentRoute: () => CustomersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/business-profile': typeof BusinessProfileRoute
  '/forgot-password': typeof ForgotPasswordRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/language': typeof LanguageRoute
  '/new-order': typeof NewOrderRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payment-details': typeof PaymentDetailsRoute
  '/payment-setup': typeof PaymentSetupRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/splash': typeof SplashRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/forgot-password/reset': typeof ForgotPasswordResetRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/business-profile': typeof BusinessProfileRoute
  '/forgot-password': typeof ForgotPasswordRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/language': typeof LanguageRoute
  '/new-order': typeof NewOrderRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payment-details': typeof PaymentDetailsRoute
  '/payment-setup': typeof PaymentSetupRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/splash': typeof SplashRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/forgot-password/reset': typeof ForgotPasswordResetRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/customers': typeof CustomersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/business-profile': typeof BusinessProfileRoute
  '/forgot-password': typeof ForgotPasswordRouteWithChildren
  '/inventory': typeof InventoryRoute
  '/language': typeof LanguageRoute
  '/new-order': typeof NewOrderRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payment-details': typeof PaymentDetailsRoute
  '/payment-setup': typeof PaymentSetupRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/search': typeof SearchRoute
  '/splash': typeof SplashRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/forgot-password/reset': typeof ForgotPasswordResetRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/customers/': typeof CustomersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/business-profile'
    | '/forgot-password'
    | '/inventory'
    | '/language'
    | '/new-order'
    | '/notification-settings'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/payment-details'
    | '/payment-setup'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/search'
    | '/splash'
    | '/customers/$customerId'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/orders/$orderId'
    | '/customers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/business-profile'
    | '/forgot-password'
    | '/inventory'
    | '/language'
    | '/new-order'
    | '/notification-settings'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/payment-details'
    | '/payment-setup'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/search'
    | '/splash'
    | '/customers/$customerId'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/orders/$orderId'
    | '/customers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/business-profile'
    | '/forgot-password'
    | '/inventory'
    | '/language'
    | '/new-order'
    | '/notification-settings'
    | '/notifications'
    | '/onboarding'
    | '/orders'
    | '/payment-details'
    | '/payment-setup'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/reports'
    | '/search'
    | '/splash'
    | '/customers/$customerId'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/orders/$orderId'
    | '/customers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  BusinessProfileRoute: typeof BusinessProfileRoute
  ForgotPasswordRoute: typeof ForgotPasswordRouteWithChildren
  InventoryRoute: typeof InventoryRoute
  LanguageRoute: typeof LanguageRoute
  NewOrderRoute: typeof NewOrderRoute
  NotificationSettingsRoute: typeof NotificationSettingsRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PaymentDetailsRoute: typeof PaymentDetailsRoute
  PaymentSetupRoute: typeof PaymentSetupRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  SearchRoute: typeof SearchRoute
  SplashRoute: typeof SplashRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-setup': {
      id: '/payment-setup'
      path: '/payment-setup'
      fullPath: '/payment-setup'
      preLoaderRoute: typeof PaymentSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-details': {
      id: '/payment-details'
      path: '/payment-details'
      fullPath: '/payment-details'
      preLoaderRoute: typeof PaymentDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification-settings': {
      id: '/notification-settings'
      path: '/notification-settings'
      fullPath: '/notification-settings'
      preLoaderRoute: typeof NotificationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-order': {
      id: '/new-order'
      path: '/new-order'
      fullPath: '/new-order'
      preLoaderRoute: typeof NewOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-profile': {
      id: '/business-profile'
      path: '/business-profile'
      fullPath: '/business-profile'
      preLoaderRoute: typeof BusinessProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/forgot-password/verify': {
      id: '/forgot-password/verify'
      path: '/verify'
      fullPath: '/forgot-password/verify'
      preLoaderRoute: typeof ForgotPasswordVerifyRouteImport
      parentRoute: typeof ForgotPasswordRoute
    }
    '/forgot-password/reset': {
      id: '/forgot-password/reset'
      path: '/reset'
      fullPath: '/forgot-password/reset'
      preLoaderRoute: typeof ForgotPasswordResetRouteImport
      parentRoute: typeof ForgotPasswordRoute
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof CustomersRoute
    }
  }
}

interface ForgotPasswordRouteChildren {
  ForgotPasswordResetRoute: typeof ForgotPasswordResetRoute
  ForgotPasswordVerifyRoute: typeof ForgotPasswordVerifyRoute
}

const ForgotPasswordRouteChildren: ForgotPasswordRouteChildren = {
  ForgotPasswordResetRoute: ForgotPasswordResetRoute,
  ForgotPasswordVerifyRoute: ForgotPasswordVerifyRoute,
}

const ForgotPasswordRouteWithChildren = ForgotPasswordRoute._addFileChildren(
  ForgotPasswordRouteChildren,
)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  BusinessProfileRoute: BusinessProfileRoute,
  ForgotPasswordRoute: ForgotPasswordRouteWithChildren,
  InventoryRoute: InventoryRoute,
  LanguageRoute: LanguageRoute,
  NewOrderRoute: NewOrderRoute,
  NotificationSettingsRoute: NotificationSettingsRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PaymentDetailsRoute: PaymentDetailsRoute,
  PaymentSetupRoute: PaymentSetupRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  SearchRoute: SearchRoute,
  SplashRoute: SplashRoute,
  CustomersIndexRoute: CustomersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
