/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappTemplatesRouteImport } from './routes/whatsapp-templates'
import { Route as ViewingsRouteImport } from './routes/viewings'
import { Route as UniversityInsightsRouteImport } from './routes/university-insights'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TeamRouteImport } from './routes/team'
import { Route as TablesRouteImport } from './routes/tables'
import { Route as SuppliersRouteImport } from './routes/suppliers'
import { Route as StockTakeRouteImport } from './routes/stock-take'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SplashRouteImport } from './routes/splash'
import { Route as ServicesSummaryRouteImport } from './routes/services-summary'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RequirementsRouteImport } from './routes/requirements'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RenewalsRouteImport } from './routes/renewals'
import { Route as RecipesRouteImport } from './routes/recipes'
import { Route as PurchaseOrdersRouteImport } from './routes/purchase-orders'
import { Route as ProfitRouteImport } from './routes/profit'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PipelineOverviewRouteImport } from './routes/pipeline-overview'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentSetupRouteImport } from './routes/payment-setup'
import { Route as PaymentDetailsRouteImport } from './routes/payment-details'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OrderFormRouteImport } from './routes/order-form'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotificationSettingsRouteImport } from './routes/notification-settings'
import { Route as NewOrderRouteImport } from './routes/new-order'
import { Route as NewBookingRouteImport } from './routes/new-booking'
import { Route as MoreRouteImport } from './routes/more'
import { Route as LoanCalculatorRouteImport } from './routes/loan-calculator'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as LanguageRouteImport } from './routes/language'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as IngredientsRouteImport } from './routes/ingredients'
import { Route as ImportOrdersRouteImport } from './routes/import-orders'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DineInRouteImport } from './routes/dine-in'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as DeliverySettingsRouteImport } from './routes/delivery-settings'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as CommissionsRouteImport } from './routes/commissions'
import { Route as ClientsCompareRouteImport } from './routes/clients-compare'
import { Route as BusinessTypeRouteImport } from './routes/business-type'
import { Route as BusinessProfileRouteImport } from './routes/business-profile'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as BookingSettingsRouteImport } from './routes/booking-settings'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ViewingIdRouteImport } from './routes/viewing.$id'
import { Route as TrackOrderRefRouteImport } from './routes/track.$orderRef'
import { Route as TeamWelcomeRouteImport } from './routes/team.welcome'
import { Route as StockTakeIdRouteImport } from './routes/stock-take_.$id'
import { Route as RequirementIdRouteImport } from './routes/requirement.$id'
import { Route as ReportsSalesRouteImport } from './routes/reports.sales'
import { Route as RenewalIdRouteImport } from './routes/renewal.$id'
import { Route as PurchaseOrdersIdRouteImport } from './routes/purchase-orders_.$id'
import { Route as OrdersOrderIdRouteImport } from './routes/orders.$orderId'
import { Route as OrderCodeRouteImport } from './routes/order.$code'
import { Route as ListingIdRouteImport } from './routes/listing.$id'
import { Route as InventoryItemIdRouteImport } from './routes/inventory.$itemId'
import { Route as ForgotPasswordVerifyRouteImport } from './routes/forgot-password.verify'
import { Route as ForgotPasswordResetRouteImport } from './routes/forgot-password.reset'
import { Route as DocumentIdRouteImport } from './routes/document.$id'
import { Route as DineTableIdRouteImport } from './routes/dine/$tableId'
import { Route as CustomerCustomerIdRouteImport } from './routes/customer.$customerId'
import { Route as ConnectedPlatformsPlatformRouteImport } from './routes/connected-platforms.$platform'
import { Route as CommissionIdRouteImport } from './routes/commission.$id'
import { Route as BookCodeRouteImport } from './routes/book.$code'
import { Route as TeamJoinTokenRouteImport } from './routes/team.join.$token'
import { Route as ApiPublicTrackingRouteImport } from './routes/api/public/tracking'
import { Route as ApiPublicOrderFormRouteImport } from './routes/api/public/order-form'
import { Route as ApiPublicDeliveryQuoteRouteImport } from './routes/api/public/delivery-quote'
import { Route as ApiPublicAdminRouteImport } from './routes/api/public/admin'
import { Route as ApiPublicWebhooksTiktokRouteImport } from './routes/api/public/webhooks/tiktok'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'
import { Route as ApiPublicStripeCheckoutRouteImport } from './routes/api/public/stripe/checkout'
import { Route as ApiPublicStripeActivateRouteImport } from './routes/api/public/stripe/activate'
import { Route as ApiPublicOauthTiktokCallbackRouteImport } from './routes/api/public/oauth/tiktok/callback'

const WhatsappTemplatesRoute = WhatsappTemplatesRouteImport.update({
  id: '/whatsapp-templates',
  path: '/whatsapp-templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ViewingsRoute = ViewingsRouteImport.update({
  id: '/viewings',
  path: '/viewings',
  getParentRoute: () => rootRouteImport,
} as any)
const UniversityInsightsRoute = UniversityInsightsRouteImport.update({
  id: '/university-insights',
  path: '/university-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const TablesRoute = TablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersRoute = SuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => rootRouteImport,
} as any)
const StockTakeRoute = StockTakeRouteImport.update({
  id: '/stock-take',
  path: '/stock-take',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SplashRoute = SplashRouteImport.update({
  id: '/splash',
  path: '/splash',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSummaryRoute = ServicesSummaryRouteImport.update({
  id: '/services-summary',
  path: '/services-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementsRoute = RequirementsRouteImport.update({
  id: '/requirements',
  path: '/requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewalsRoute = RenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesRoute = RecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersRoute = PurchaseOrdersRouteImport.update({
  id: '/purchase-orders',
  path: '/purchase-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfitRoute = ProfitRouteImport.update({
  id: '/profit',
  path: '/profit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineOverviewRoute = PipelineOverviewRouteImport.update({
  id: '/pipeline-overview',
  path: '/pipeline-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSetupRoute = PaymentSetupRouteImport.update({
  id: '/payment-setup',
  path: '/payment-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentDetailsRoute = PaymentDetailsRouteImport.update({
  id: '/payment-details',
  path: '/payment-details',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderFormRoute = OrderFormRouteImport.update({
  id: '/order-form',
  path: '/order-form',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationSettingsRoute = NotificationSettingsRouteImport.update({
  id: '/notification-settings',
  path: '/notification-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const NewOrderRoute = NewOrderRouteImport.update({
  id: '/new-order',
  path: '/new-order',
  getParentRoute: () => rootRouteImport,
} as any)
const NewBookingRoute = NewBookingRouteImport.update({
  id: '/new-booking',
  path: '/new-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const LoanCalculatorRoute = LoanCalculatorRouteImport.update({
  id: '/loan-calculator',
  path: '/loan-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguageRoute = LanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const IngredientsRoute = IngredientsRouteImport.update({
  id: '/ingredients',
  path: '/ingredients',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportOrdersRoute = ImportOrdersRouteImport.update({
  id: '/import-orders',
  path: '/import-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DineInRoute = DineInRouteImport.update({
  id: '/dine-in',
  path: '/dine-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliverySettingsRoute = DeliverySettingsRouteImport.update({
  id: '/delivery-settings',
  path: '/delivery-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const CommissionsRoute = CommissionsRouteImport.update({
  id: '/commissions',
  path: '/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsCompareRoute = ClientsCompareRouteImport.update({
  id: '/clients-compare',
  path: '/clients-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessTypeRoute = BusinessTypeRouteImport.update({
  id: '/business-type',
  path: '/business-type',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessProfileRoute = BusinessProfileRouteImport.update({
  id: '/business-profile',
  path: '/business-profile',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSettingsRoute = BookingSettingsRouteImport.update({
  id: '/booking-settings',
  path: '/booking-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ViewingIdRoute = ViewingIdRouteImport.update({
  id: '/viewing/$id',
  path: '/viewing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRefRoute = TrackOrderRefRouteImport.update({
  id: '/track/$orderRef',
  path: '/track/$orderRef',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamWelcomeRoute = TeamWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => TeamRoute,
} as any)
const StockTakeIdRoute = StockTakeIdRouteImport.update({
  id: '/stock-take_/$id',
  path: '/stock-take/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RequirementIdRoute = RequirementIdRouteImport.update({
  id: '/requirement/$id',
  path: '/requirement/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsSalesRoute = ReportsSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => ReportsRoute,
} as any)
const RenewalIdRoute = RenewalIdRouteImport.update({
  id: '/renewal/$id',
  path: '/renewal/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseOrdersIdRoute = PurchaseOrdersIdRouteImport.update({
  id: '/purchase-orders_/$id',
  path: '/purchase-orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => OrdersRoute,
} as any)
const OrderCodeRoute = OrderCodeRouteImport.update({
  id: '/order/$code',
  path: '/order/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingIdRoute = ListingIdRouteImport.update({
  id: '/listing/$id',
  path: '/listing/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryItemIdRoute = InventoryItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => InventoryRoute,
} as any)
const ForgotPasswordVerifyRoute = ForgotPasswordVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => ForgotPasswordRoute,
} as any)
const ForgotPasswordResetRoute = ForgotPasswordResetRouteImport.update({
  id: '/reset',
  path: '/reset',
  getParentRoute: () => ForgotPasswordRoute,
} as any)
const DocumentIdRoute = DocumentIdRouteImport.update({
  id: '/document/$id',
  path: '/document/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DineTableIdRoute = DineTableIdRouteImport.update({
  id: '/dine/$tableId',
  path: '/dine/$tableId',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerCustomerIdRoute = CustomerCustomerIdRouteImport.update({
  id: '/customer/$customerId',
  path: '/customer/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectedPlatformsPlatformRoute =
  ConnectedPlatformsPlatformRouteImport.update({
    id: '/connected-platforms/$platform',
    path: '/connected-platforms/$platform',
    getParentRoute: () => rootRouteImport,
  } as any)
const CommissionIdRoute = CommissionIdRouteImport.update({
  id: '/commission/$id',
  path: '/commission/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookCodeRoute = BookCodeRouteImport.update({
  id: '/book/$code',
  path: '/book/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamJoinTokenRoute = TeamJoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => TeamRoute,
} as any)
const ApiPublicTrackingRoute = ApiPublicTrackingRouteImport.update({
  id: '/api/public/tracking',
  path: '/api/public/tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOrderFormRoute = ApiPublicOrderFormRouteImport.update({
  id: '/api/public/order-form',
  path: '/api/public/order-form',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDeliveryQuoteRoute = ApiPublicDeliveryQuoteRouteImport.update({
  id: '/api/public/delivery-quote',
  path: '/api/public/delivery-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAdminRoute = ApiPublicAdminRouteImport.update({
  id: '/api/public/admin',
  path: '/api/public/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksTiktokRoute = ApiPublicWebhooksTiktokRouteImport.update({
  id: '/api/public/webhooks/tiktok',
  path: '/api/public/webhooks/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeCheckoutRoute = ApiPublicStripeCheckoutRouteImport.update({
  id: '/api/public/stripe/checkout',
  path: '/api/public/stripe/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeActivateRoute = ApiPublicStripeActivateRouteImport.update({
  id: '/api/public/stripe/activate',
  path: '/api/public/stripe/activate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthTiktokCallbackRoute =
  ApiPublicOauthTiktokCallbackRouteImport.update({
    id: '/api/public/oauth/tiktok/callback',
    path: '/api/public/oauth/tiktok/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/booking-settings': typeof BookingSettingsRoute
  '/bookings': typeof BookingsRoute
  '/business-profile': typeof BusinessProfileRoute
  '/business-type': typeof BusinessTypeRoute
  '/clients-compare': typeof ClientsCompareRoute
  '/commissions': typeof CommissionsRoute
  '/customers': typeof CustomersRoute
  '/data-deletion': typeof DataDeletionRoute
  '/delivery-settings': typeof DeliverySettingsRoute
  '/devices': typeof DevicesRoute
  '/dine-in': typeof DineInRoute
  '/documents': typeof DocumentsRoute
  '/forgot-password': typeof ForgotPasswordRouteWithChildren
  '/import-orders': typeof ImportOrdersRoute
  '/ingredients': typeof IngredientsRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/language': typeof LanguageRoute
  '/legal': typeof LegalRoute
  '/listings': typeof ListingsRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/more': typeof MoreRoute
  '/new-booking': typeof NewBookingRoute
  '/new-order': typeof NewOrderRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/order-form': typeof OrderFormRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payment-details': typeof PaymentDetailsRoute
  '/payment-setup': typeof PaymentSetupRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pipeline-overview': typeof PipelineOverviewRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/profit': typeof ProfitRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/recipes': typeof RecipesRoute
  '/renewals': typeof RenewalsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/requirements': typeof RequirementsRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/services-summary': typeof ServicesSummaryRoute
  '/splash': typeof SplashRoute
  '/stock': typeof StockRoute
  '/stock-take': typeof StockTakeRoute
  '/suppliers': typeof SuppliersRoute
  '/tables': typeof TablesRoute
  '/team': typeof TeamRouteWithChildren
  '/terms': typeof TermsRoute
  '/university-insights': typeof UniversityInsightsRoute
  '/viewings': typeof ViewingsRoute
  '/whatsapp-templates': typeof WhatsappTemplatesRoute
  '/book/$code': typeof BookCodeRoute
  '/commission/$id': typeof CommissionIdRoute
  '/connected-platforms/$platform': typeof ConnectedPlatformsPlatformRoute
  '/customer/$customerId': typeof CustomerCustomerIdRoute
  '/dine/$tableId': typeof DineTableIdRoute
  '/document/$id': typeof DocumentIdRoute
  '/forgot-password/reset': typeof ForgotPasswordResetRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/order/$code': typeof OrderCodeRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/purchase-orders/$id': typeof PurchaseOrdersIdRoute
  '/renewal/$id': typeof RenewalIdRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/requirement/$id': typeof RequirementIdRoute
  '/stock-take/$id': typeof StockTakeIdRoute
  '/team/welcome': typeof TeamWelcomeRoute
  '/track/$orderRef': typeof TrackOrderRefRoute
  '/viewing/$id': typeof ViewingIdRoute
  '/reports/': typeof ReportsIndexRoute
  '/api/public/admin': typeof ApiPublicAdminRoute
  '/api/public/delivery-quote': typeof ApiPublicDeliveryQuoteRoute
  '/api/public/order-form': typeof ApiPublicOrderFormRoute
  '/api/public/tracking': typeof ApiPublicTrackingRoute
  '/team/join/$token': typeof TeamJoinTokenRoute
  '/api/public/stripe/activate': typeof ApiPublicStripeActivateRoute
  '/api/public/stripe/checkout': typeof ApiPublicStripeCheckoutRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/webhooks/tiktok': typeof ApiPublicWebhooksTiktokRoute
  '/api/public/oauth/tiktok/callback': typeof ApiPublicOauthTiktokCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/booking-settings': typeof BookingSettingsRoute
  '/bookings': typeof BookingsRoute
  '/business-profile': typeof BusinessProfileRoute
  '/business-type': typeof BusinessTypeRoute
  '/clients-compare': typeof ClientsCompareRoute
  '/commissions': typeof CommissionsRoute
  '/customers': typeof CustomersRoute
  '/data-deletion': typeof DataDeletionRoute
  '/delivery-settings': typeof DeliverySettingsRoute
  '/devices': typeof DevicesRoute
  '/dine-in': typeof DineInRoute
  '/documents': typeof DocumentsRoute
  '/forgot-password': typeof ForgotPasswordRouteWithChildren
  '/import-orders': typeof ImportOrdersRoute
  '/ingredients': typeof IngredientsRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/language': typeof LanguageRoute
  '/legal': typeof LegalRoute
  '/listings': typeof ListingsRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/more': typeof MoreRoute
  '/new-booking': typeof NewBookingRoute
  '/new-order': typeof NewOrderRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/order-form': typeof OrderFormRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payment-details': typeof PaymentDetailsRoute
  '/payment-setup': typeof PaymentSetupRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pipeline-overview': typeof PipelineOverviewRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/profit': typeof ProfitRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/recipes': typeof RecipesRoute
  '/renewals': typeof RenewalsRoute
  '/requirements': typeof RequirementsRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/services-summary': typeof ServicesSummaryRoute
  '/splash': typeof SplashRoute
  '/stock': typeof StockRoute
  '/stock-take': typeof StockTakeRoute
  '/suppliers': typeof SuppliersRoute
  '/tables': typeof TablesRoute
  '/team': typeof TeamRouteWithChildren
  '/terms': typeof TermsRoute
  '/university-insights': typeof UniversityInsightsRoute
  '/viewings': typeof ViewingsRoute
  '/whatsapp-templates': typeof WhatsappTemplatesRoute
  '/book/$code': typeof BookCodeRoute
  '/commission/$id': typeof CommissionIdRoute
  '/connected-platforms/$platform': typeof ConnectedPlatformsPlatformRoute
  '/customer/$customerId': typeof CustomerCustomerIdRoute
  '/dine/$tableId': typeof DineTableIdRoute
  '/document/$id': typeof DocumentIdRoute
  '/forgot-password/reset': typeof ForgotPasswordResetRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/order/$code': typeof OrderCodeRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/purchase-orders/$id': typeof PurchaseOrdersIdRoute
  '/renewal/$id': typeof RenewalIdRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/requirement/$id': typeof RequirementIdRoute
  '/stock-take/$id': typeof StockTakeIdRoute
  '/team/welcome': typeof TeamWelcomeRoute
  '/track/$orderRef': typeof TrackOrderRefRoute
  '/viewing/$id': typeof ViewingIdRoute
  '/reports': typeof ReportsIndexRoute
  '/api/public/admin': typeof ApiPublicAdminRoute
  '/api/public/delivery-quote': typeof ApiPublicDeliveryQuoteRoute
  '/api/public/order-form': typeof ApiPublicOrderFormRoute
  '/api/public/tracking': typeof ApiPublicTrackingRoute
  '/team/join/$token': typeof TeamJoinTokenRoute
  '/api/public/stripe/activate': typeof ApiPublicStripeActivateRoute
  '/api/public/stripe/checkout': typeof ApiPublicStripeCheckoutRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/webhooks/tiktok': typeof ApiPublicWebhooksTiktokRoute
  '/api/public/oauth/tiktok/callback': typeof ApiPublicOauthTiktokCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/booking-settings': typeof BookingSettingsRoute
  '/bookings': typeof BookingsRoute
  '/business-profile': typeof BusinessProfileRoute
  '/business-type': typeof BusinessTypeRoute
  '/clients-compare': typeof ClientsCompareRoute
  '/commissions': typeof CommissionsRoute
  '/customers': typeof CustomersRoute
  '/data-deletion': typeof DataDeletionRoute
  '/delivery-settings': typeof DeliverySettingsRoute
  '/devices': typeof DevicesRoute
  '/dine-in': typeof DineInRoute
  '/documents': typeof DocumentsRoute
  '/forgot-password': typeof ForgotPasswordRouteWithChildren
  '/import-orders': typeof ImportOrdersRoute
  '/ingredients': typeof IngredientsRoute
  '/inventory': typeof InventoryRouteWithChildren
  '/language': typeof LanguageRoute
  '/legal': typeof LegalRoute
  '/listings': typeof ListingsRoute
  '/loan-calculator': typeof LoanCalculatorRoute
  '/more': typeof MoreRoute
  '/new-booking': typeof NewBookingRoute
  '/new-order': typeof NewOrderRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/order-form': typeof OrderFormRoute
  '/orders': typeof OrdersRouteWithChildren
  '/payment-details': typeof PaymentDetailsRoute
  '/payment-setup': typeof PaymentSetupRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/pipeline-overview': typeof PipelineOverviewRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/profit': typeof ProfitRoute
  '/purchase-orders': typeof PurchaseOrdersRoute
  '/recipes': typeof RecipesRoute
  '/renewals': typeof RenewalsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/requirements': typeof RequirementsRoute
  '/search': typeof SearchRoute
  '/services': typeof ServicesRoute
  '/services-summary': typeof ServicesSummaryRoute
  '/splash': typeof SplashRoute
  '/stock': typeof StockRoute
  '/stock-take': typeof StockTakeRoute
  '/suppliers': typeof SuppliersRoute
  '/tables': typeof TablesRoute
  '/team': typeof TeamRouteWithChildren
  '/terms': typeof TermsRoute
  '/university-insights': typeof UniversityInsightsRoute
  '/viewings': typeof ViewingsRoute
  '/whatsapp-templates': typeof WhatsappTemplatesRoute
  '/book/$code': typeof BookCodeRoute
  '/commission/$id': typeof CommissionIdRoute
  '/connected-platforms/$platform': typeof ConnectedPlatformsPlatformRoute
  '/customer/$customerId': typeof CustomerCustomerIdRoute
  '/dine/$tableId': typeof DineTableIdRoute
  '/document/$id': typeof DocumentIdRoute
  '/forgot-password/reset': typeof ForgotPasswordResetRoute
  '/forgot-password/verify': typeof ForgotPasswordVerifyRoute
  '/inventory/$itemId': typeof InventoryItemIdRoute
  '/listing/$id': typeof ListingIdRoute
  '/order/$code': typeof OrderCodeRoute
  '/orders/$orderId': typeof OrdersOrderIdRoute
  '/purchase-orders_/$id': typeof PurchaseOrdersIdRoute
  '/renewal/$id': typeof RenewalIdRoute
  '/reports/sales': typeof ReportsSalesRoute
  '/requirement/$id': typeof RequirementIdRoute
  '/stock-take_/$id': typeof StockTakeIdRoute
  '/team/welcome': typeof TeamWelcomeRoute
  '/track/$orderRef': typeof TrackOrderRefRoute
  '/viewing/$id': typeof ViewingIdRoute
  '/reports/': typeof ReportsIndexRoute
  '/api/public/admin': typeof ApiPublicAdminRoute
  '/api/public/delivery-quote': typeof ApiPublicDeliveryQuoteRoute
  '/api/public/order-form': typeof ApiPublicOrderFormRoute
  '/api/public/tracking': typeof ApiPublicTrackingRoute
  '/team/join/$token': typeof TeamJoinTokenRoute
  '/api/public/stripe/activate': typeof ApiPublicStripeActivateRoute
  '/api/public/stripe/checkout': typeof ApiPublicStripeCheckoutRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/webhooks/tiktok': typeof ApiPublicWebhooksTiktokRoute
  '/api/public/oauth/tiktok/callback': typeof ApiPublicOauthTiktokCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/auth'
    | '/booking-settings'
    | '/bookings'
    | '/business-profile'
    | '/business-type'
    | '/clients-compare'
    | '/commissions'
    | '/customers'
    | '/data-deletion'
    | '/delivery-settings'
    | '/devices'
    | '/dine-in'
    | '/documents'
    | '/forgot-password'
    | '/import-orders'
    | '/ingredients'
    | '/inventory'
    | '/language'
    | '/legal'
    | '/listings'
    | '/loan-calculator'
    | '/more'
    | '/new-booking'
    | '/new-order'
    | '/notification-settings'
    | '/notifications'
    | '/onboarding'
    | '/order-form'
    | '/orders'
    | '/payment-details'
    | '/payment-setup'
    | '/payment-success'
    | '/pipeline-overview'
    | '/plans'
    | '/privacy'
    | '/privacy-policy'
    | '/profile'
    | '/profit'
    | '/purchase-orders'
    | '/recipes'
    | '/renewals'
    | '/reports'
    | '/requirements'
    | '/search'
    | '/services'
    | '/services-summary'
    | '/splash'
    | '/stock'
    | '/stock-take'
    | '/suppliers'
    | '/tables'
    | '/team'
    | '/terms'
    | '/university-insights'
    | '/viewings'
    | '/whatsapp-templates'
    | '/book/$code'
    | '/commission/$id'
    | '/connected-platforms/$platform'
    | '/customer/$customerId'
    | '/dine/$tableId'
    | '/document/$id'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/inventory/$itemId'
    | '/listing/$id'
    | '/order/$code'
    | '/orders/$orderId'
    | '/purchase-orders/$id'
    | '/renewal/$id'
    | '/reports/sales'
    | '/requirement/$id'
    | '/stock-take/$id'
    | '/team/welcome'
    | '/track/$orderRef'
    | '/viewing/$id'
    | '/reports/'
    | '/api/public/admin'
    | '/api/public/delivery-quote'
    | '/api/public/order-form'
    | '/api/public/tracking'
    | '/team/join/$token'
    | '/api/public/stripe/activate'
    | '/api/public/stripe/checkout'
    | '/api/public/stripe/webhook'
    | '/api/public/webhooks/tiktok'
    | '/api/public/oauth/tiktok/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/auth'
    | '/booking-settings'
    | '/bookings'
    | '/business-profile'
    | '/business-type'
    | '/clients-compare'
    | '/commissions'
    | '/customers'
    | '/data-deletion'
    | '/delivery-settings'
    | '/devices'
    | '/dine-in'
    | '/documents'
    | '/forgot-password'
    | '/import-orders'
    | '/ingredients'
    | '/inventory'
    | '/language'
    | '/legal'
    | '/listings'
    | '/loan-calculator'
    | '/more'
    | '/new-booking'
    | '/new-order'
    | '/notification-settings'
    | '/notifications'
    | '/onboarding'
    | '/order-form'
    | '/orders'
    | '/payment-details'
    | '/payment-setup'
    | '/payment-success'
    | '/pipeline-overview'
    | '/plans'
    | '/privacy'
    | '/privacy-policy'
    | '/profile'
    | '/profit'
    | '/purchase-orders'
    | '/recipes'
    | '/renewals'
    | '/requirements'
    | '/search'
    | '/services'
    | '/services-summary'
    | '/splash'
    | '/stock'
    | '/stock-take'
    | '/suppliers'
    | '/tables'
    | '/team'
    | '/terms'
    | '/university-insights'
    | '/viewings'
    | '/whatsapp-templates'
    | '/book/$code'
    | '/commission/$id'
    | '/connected-platforms/$platform'
    | '/customer/$customerId'
    | '/dine/$tableId'
    | '/document/$id'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/inventory/$itemId'
    | '/listing/$id'
    | '/order/$code'
    | '/orders/$orderId'
    | '/purchase-orders/$id'
    | '/renewal/$id'
    | '/reports/sales'
    | '/requirement/$id'
    | '/stock-take/$id'
    | '/team/welcome'
    | '/track/$orderRef'
    | '/viewing/$id'
    | '/reports'
    | '/api/public/admin'
    | '/api/public/delivery-quote'
    | '/api/public/order-form'
    | '/api/public/tracking'
    | '/team/join/$token'
    | '/api/public/stripe/activate'
    | '/api/public/stripe/checkout'
    | '/api/public/stripe/webhook'
    | '/api/public/webhooks/tiktok'
    | '/api/public/oauth/tiktok/callback'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/alerts'
    | '/analytics'
    | '/auth'
    | '/booking-settings'
    | '/bookings'
    | '/business-profile'
    | '/business-type'
    | '/clients-compare'
    | '/commissions'
    | '/customers'
    | '/data-deletion'
    | '/delivery-settings'
    | '/devices'
    | '/dine-in'
    | '/documents'
    | '/forgot-password'
    | '/import-orders'
    | '/ingredients'
    | '/inventory'
    | '/language'
    | '/legal'
    | '/listings'
    | '/loan-calculator'
    | '/more'
    | '/new-booking'
    | '/new-order'
    | '/notification-settings'
    | '/notifications'
    | '/onboarding'
    | '/order-form'
    | '/orders'
    | '/payment-details'
    | '/payment-setup'
    | '/payment-success'
    | '/pipeline-overview'
    | '/plans'
    | '/privacy'
    | '/privacy-policy'
    | '/profile'
    | '/profit'
    | '/purchase-orders'
    | '/recipes'
    | '/renewals'
    | '/reports'
    | '/requirements'
    | '/search'
    | '/services'
    | '/services-summary'
    | '/splash'
    | '/stock'
    | '/stock-take'
    | '/suppliers'
    | '/tables'
    | '/team'
    | '/terms'
    | '/university-insights'
    | '/viewings'
    | '/whatsapp-templates'
    | '/book/$code'
    | '/commission/$id'
    | '/connected-platforms/$platform'
    | '/customer/$customerId'
    | '/dine/$tableId'
    | '/document/$id'
    | '/forgot-password/reset'
    | '/forgot-password/verify'
    | '/inventory/$itemId'
    | '/listing/$id'
    | '/order/$code'
    | '/orders/$orderId'
    | '/purchase-orders_/$id'
    | '/renewal/$id'
    | '/reports/sales'
    | '/requirement/$id'
    | '/stock-take_/$id'
    | '/team/welcome'
    | '/track/$orderRef'
    | '/viewing/$id'
    | '/reports/'
    | '/api/public/admin'
    | '/api/public/delivery-quote'
    | '/api/public/order-form'
    | '/api/public/tracking'
    | '/team/join/$token'
    | '/api/public/stripe/activate'
    | '/api/public/stripe/checkout'
    | '/api/public/stripe/webhook'
    | '/api/public/webhooks/tiktok'
    | '/api/public/oauth/tiktok/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  BookingSettingsRoute: typeof BookingSettingsRoute
  BookingsRoute: typeof BookingsRoute
  BusinessProfileRoute: typeof BusinessProfileRoute
  BusinessTypeRoute: typeof BusinessTypeRoute
  ClientsCompareRoute: typeof ClientsCompareRoute
  CommissionsRoute: typeof CommissionsRoute
  CustomersRoute: typeof CustomersRoute
  DataDeletionRoute: typeof DataDeletionRoute
  DeliverySettingsRoute: typeof DeliverySettingsRoute
  DevicesRoute: typeof DevicesRoute
  DineInRoute: typeof DineInRoute
  DocumentsRoute: typeof DocumentsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRouteWithChildren
  ImportOrdersRoute: typeof ImportOrdersRoute
  IngredientsRoute: typeof IngredientsRoute
  InventoryRoute: typeof InventoryRouteWithChildren
  LanguageRoute: typeof LanguageRoute
  LegalRoute: typeof LegalRoute
  ListingsRoute: typeof ListingsRoute
  LoanCalculatorRoute: typeof LoanCalculatorRoute
  MoreRoute: typeof MoreRoute
  NewBookingRoute: typeof NewBookingRoute
  NewOrderRoute: typeof NewOrderRoute
  NotificationSettingsRoute: typeof NotificationSettingsRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  OrderFormRoute: typeof OrderFormRoute
  OrdersRoute: typeof OrdersRouteWithChildren
  PaymentDetailsRoute: typeof PaymentDetailsRoute
  PaymentSetupRoute: typeof PaymentSetupRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  PipelineOverviewRoute: typeof PipelineOverviewRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  ProfitRoute: typeof ProfitRoute
  PurchaseOrdersRoute: typeof PurchaseOrdersRoute
  RecipesRoute: typeof RecipesRoute
  RenewalsRoute: typeof RenewalsRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  RequirementsRoute: typeof RequirementsRoute
  SearchRoute: typeof SearchRoute
  ServicesRoute: typeof ServicesRoute
  ServicesSummaryRoute: typeof ServicesSummaryRoute
  SplashRoute: typeof SplashRoute
  StockRoute: typeof StockRoute
  StockTakeRoute: typeof StockTakeRoute
  SuppliersRoute: typeof SuppliersRoute
  TablesRoute: typeof TablesRoute
  TeamRoute: typeof TeamRouteWithChildren
  TermsRoute: typeof TermsRoute
  UniversityInsightsRoute: typeof UniversityInsightsRoute
  ViewingsRoute: typeof ViewingsRoute
  WhatsappTemplatesRoute: typeof WhatsappTemplatesRoute
  BookCodeRoute: typeof BookCodeRoute
  CommissionIdRoute: typeof CommissionIdRoute
  ConnectedPlatformsPlatformRoute: typeof ConnectedPlatformsPlatformRoute
  CustomerCustomerIdRoute: typeof CustomerCustomerIdRoute
  DineTableIdRoute: typeof DineTableIdRoute
  DocumentIdRoute: typeof DocumentIdRoute
  ListingIdRoute: typeof ListingIdRoute
  OrderCodeRoute: typeof OrderCodeRoute
  PurchaseOrdersIdRoute: typeof PurchaseOrdersIdRoute
  RenewalIdRoute: typeof RenewalIdRoute
  RequirementIdRoute: typeof RequirementIdRoute
  StockTakeIdRoute: typeof StockTakeIdRoute
  TrackOrderRefRoute: typeof TrackOrderRefRoute
  ViewingIdRoute: typeof ViewingIdRoute
  ApiPublicAdminRoute: typeof ApiPublicAdminRoute
  ApiPublicDeliveryQuoteRoute: typeof ApiPublicDeliveryQuoteRoute
  ApiPublicOrderFormRoute: typeof ApiPublicOrderFormRoute
  ApiPublicTrackingRoute: typeof ApiPublicTrackingRoute
  ApiPublicStripeActivateRoute: typeof ApiPublicStripeActivateRoute
  ApiPublicStripeCheckoutRoute: typeof ApiPublicStripeCheckoutRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicWebhooksTiktokRoute: typeof ApiPublicWebhooksTiktokRoute
  ApiPublicOauthTiktokCallbackRoute: typeof ApiPublicOauthTiktokCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp-templates': {
      id: '/whatsapp-templates'
      path: '/whatsapp-templates'
      fullPath: '/whatsapp-templates'
      preLoaderRoute: typeof WhatsappTemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viewings': {
      id: '/viewings'
      path: '/viewings'
      fullPath: '/viewings'
      preLoaderRoute: typeof ViewingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/university-insights': {
      id: '/university-insights'
      path: '/university-insights'
      fullPath: '/university-insights'
      preLoaderRoute: typeof UniversityInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tables': {
      id: '/tables'
      path: '/tables'
      fullPath: '/tables'
      preLoaderRoute: typeof TablesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers': {
      id: '/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof SuppliersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock-take': {
      id: '/stock-take'
      path: '/stock-take'
      fullPath: '/stock-take'
      preLoaderRoute: typeof StockTakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/splash': {
      id: '/splash'
      path: '/splash'
      fullPath: '/splash'
      preLoaderRoute: typeof SplashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services-summary': {
      id: '/services-summary'
      path: '/services-summary'
      fullPath: '/services-summary'
      preLoaderRoute: typeof ServicesSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirements': {
      id: '/requirements'
      path: '/requirements'
      fullPath: '/requirements'
      preLoaderRoute: typeof RequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renewals': {
      id: '/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof RenewalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes': {
      id: '/recipes'
      path: '/recipes'
      fullPath: '/recipes'
      preLoaderRoute: typeof RecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders': {
      id: '/purchase-orders'
      path: '/purchase-orders'
      fullPath: '/purchase-orders'
      preLoaderRoute: typeof PurchaseOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profit': {
      id: '/profit'
      path: '/profit'
      fullPath: '/profit'
      preLoaderRoute: typeof ProfitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline-overview': {
      id: '/pipeline-overview'
      path: '/pipeline-overview'
      fullPath: '/pipeline-overview'
      preLoaderRoute: typeof PipelineOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-setup': {
      id: '/payment-setup'
      path: '/payment-setup'
      fullPath: '/payment-setup'
      preLoaderRoute: typeof PaymentSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-details': {
      id: '/payment-details'
      path: '/payment-details'
      fullPath: '/payment-details'
      preLoaderRoute: typeof PaymentDetailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-form': {
      id: '/order-form'
      path: '/order-form'
      fullPath: '/order-form'
      preLoaderRoute: typeof OrderFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification-settings': {
      id: '/notification-settings'
      path: '/notification-settings'
      fullPath: '/notification-settings'
      preLoaderRoute: typeof NotificationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-order': {
      id: '/new-order'
      path: '/new-order'
      fullPath: '/new-order'
      preLoaderRoute: typeof NewOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-booking': {
      id: '/new-booking'
      path: '/new-booking'
      fullPath: '/new-booking'
      preLoaderRoute: typeof NewBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loan-calculator': {
      id: '/loan-calculator'
      path: '/loan-calculator'
      fullPath: '/loan-calculator'
      preLoaderRoute: typeof LoanCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/language': {
      id: '/language'
      path: '/language'
      fullPath: '/language'
      preLoaderRoute: typeof LanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ingredients': {
      id: '/ingredients'
      path: '/ingredients'
      fullPath: '/ingredients'
      preLoaderRoute: typeof IngredientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-orders': {
      id: '/import-orders'
      path: '/import-orders'
      fullPath: '/import-orders'
      preLoaderRoute: typeof ImportOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dine-in': {
      id: '/dine-in'
      path: '/dine-in'
      fullPath: '/dine-in'
      preLoaderRoute: typeof DineInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-settings': {
      id: '/delivery-settings'
      path: '/delivery-settings'
      fullPath: '/delivery-settings'
      preLoaderRoute: typeof DeliverySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commissions': {
      id: '/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof CommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients-compare': {
      id: '/clients-compare'
      path: '/clients-compare'
      fullPath: '/clients-compare'
      preLoaderRoute: typeof ClientsCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-type': {
      id: '/business-type'
      path: '/business-type'
      fullPath: '/business-type'
      preLoaderRoute: typeof BusinessTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-profile': {
      id: '/business-profile'
      path: '/business-profile'
      fullPath: '/business-profile'
      preLoaderRoute: typeof BusinessProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-settings': {
      id: '/booking-settings'
      path: '/booking-settings'
      fullPath: '/booking-settings'
      preLoaderRoute: typeof BookingSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/viewing/$id': {
      id: '/viewing/$id'
      path: '/viewing/$id'
      fullPath: '/viewing/$id'
      preLoaderRoute: typeof ViewingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$orderRef': {
      id: '/track/$orderRef'
      path: '/track/$orderRef'
      fullPath: '/track/$orderRef'
      preLoaderRoute: typeof TrackOrderRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/welcome': {
      id: '/team/welcome'
      path: '/welcome'
      fullPath: '/team/welcome'
      preLoaderRoute: typeof TeamWelcomeRouteImport
      parentRoute: typeof TeamRoute
    }
    '/stock-take_/$id': {
      id: '/stock-take_/$id'
      path: '/stock-take/$id'
      fullPath: '/stock-take/$id'
      preLoaderRoute: typeof StockTakeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requirement/$id': {
      id: '/requirement/$id'
      path: '/requirement/$id'
      fullPath: '/requirement/$id'
      preLoaderRoute: typeof RequirementIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/sales': {
      id: '/reports/sales'
      path: '/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof ReportsSalesRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/renewal/$id': {
      id: '/renewal/$id'
      path: '/renewal/$id'
      fullPath: '/renewal/$id'
      preLoaderRoute: typeof RenewalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-orders_/$id': {
      id: '/purchase-orders_/$id'
      path: '/purchase-orders/$id'
      fullPath: '/purchase-orders/$id'
      preLoaderRoute: typeof PurchaseOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$orderId': {
      id: '/orders/$orderId'
      path: '/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof OrdersOrderIdRouteImport
      parentRoute: typeof OrdersRoute
    }
    '/order/$code': {
      id: '/order/$code'
      path: '/order/$code'
      fullPath: '/order/$code'
      preLoaderRoute: typeof OrderCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listing/$id': {
      id: '/listing/$id'
      path: '/listing/$id'
      fullPath: '/listing/$id'
      preLoaderRoute: typeof ListingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/$itemId': {
      id: '/inventory/$itemId'
      path: '/$itemId'
      fullPath: '/inventory/$itemId'
      preLoaderRoute: typeof InventoryItemIdRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/forgot-password/verify': {
      id: '/forgot-password/verify'
      path: '/verify'
      fullPath: '/forgot-password/verify'
      preLoaderRoute: typeof ForgotPasswordVerifyRouteImport
      parentRoute: typeof ForgotPasswordRoute
    }
    '/forgot-password/reset': {
      id: '/forgot-password/reset'
      path: '/reset'
      fullPath: '/forgot-password/reset'
      preLoaderRoute: typeof ForgotPasswordResetRouteImport
      parentRoute: typeof ForgotPasswordRoute
    }
    '/document/$id': {
      id: '/document/$id'
      path: '/document/$id'
      fullPath: '/document/$id'
      preLoaderRoute: typeof DocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dine/$tableId': {
      id: '/dine/$tableId'
      path: '/dine/$tableId'
      fullPath: '/dine/$tableId'
      preLoaderRoute: typeof DineTableIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/$customerId': {
      id: '/customer/$customerId'
      path: '/customer/$customerId'
      fullPath: '/customer/$customerId'
      preLoaderRoute: typeof CustomerCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connected-platforms/$platform': {
      id: '/connected-platforms/$platform'
      path: '/connected-platforms/$platform'
      fullPath: '/connected-platforms/$platform'
      preLoaderRoute: typeof ConnectedPlatformsPlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commission/$id': {
      id: '/commission/$id'
      path: '/commission/$id'
      fullPath: '/commission/$id'
      preLoaderRoute: typeof CommissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$code': {
      id: '/book/$code'
      path: '/book/$code'
      fullPath: '/book/$code'
      preLoaderRoute: typeof BookCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/join/$token': {
      id: '/team/join/$token'
      path: '/join/$token'
      fullPath: '/team/join/$token'
      preLoaderRoute: typeof TeamJoinTokenRouteImport
      parentRoute: typeof TeamRoute
    }
    '/api/public/tracking': {
      id: '/api/public/tracking'
      path: '/api/public/tracking'
      fullPath: '/api/public/tracking'
      preLoaderRoute: typeof ApiPublicTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/order-form': {
      id: '/api/public/order-form'
      path: '/api/public/order-form'
      fullPath: '/api/public/order-form'
      preLoaderRoute: typeof ApiPublicOrderFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/delivery-quote': {
      id: '/api/public/delivery-quote'
      path: '/api/public/delivery-quote'
      fullPath: '/api/public/delivery-quote'
      preLoaderRoute: typeof ApiPublicDeliveryQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin': {
      id: '/api/public/admin'
      path: '/api/public/admin'
      fullPath: '/api/public/admin'
      preLoaderRoute: typeof ApiPublicAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/tiktok': {
      id: '/api/public/webhooks/tiktok'
      path: '/api/public/webhooks/tiktok'
      fullPath: '/api/public/webhooks/tiktok'
      preLoaderRoute: typeof ApiPublicWebhooksTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/checkout': {
      id: '/api/public/stripe/checkout'
      path: '/api/public/stripe/checkout'
      fullPath: '/api/public/stripe/checkout'
      preLoaderRoute: typeof ApiPublicStripeCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/activate': {
      id: '/api/public/stripe/activate'
      path: '/api/public/stripe/activate'
      fullPath: '/api/public/stripe/activate'
      preLoaderRoute: typeof ApiPublicStripeActivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/tiktok/callback': {
      id: '/api/public/oauth/tiktok/callback'
      path: '/api/public/oauth/tiktok/callback'
      fullPath: '/api/public/oauth/tiktok/callback'
      preLoaderRoute: typeof ApiPublicOauthTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ForgotPasswordRouteChildren {
  ForgotPasswordResetRoute: typeof ForgotPasswordResetRoute
  ForgotPasswordVerifyRoute: typeof ForgotPasswordVerifyRoute
}

const ForgotPasswordRouteChildren: ForgotPasswordRouteChildren = {
  ForgotPasswordResetRoute: ForgotPasswordResetRoute,
  ForgotPasswordVerifyRoute: ForgotPasswordVerifyRoute,
}

const ForgotPasswordRouteWithChildren = ForgotPasswordRoute._addFileChildren(
  ForgotPasswordRouteChildren,
)

interface InventoryRouteChildren {
  InventoryItemIdRoute: typeof InventoryItemIdRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryItemIdRoute: InventoryItemIdRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface OrdersRouteChildren {
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute
}

const OrdersRouteChildren: OrdersRouteChildren = {
  OrdersOrderIdRoute: OrdersOrderIdRoute,
}

const OrdersRouteWithChildren =
  OrdersRoute._addFileChildren(OrdersRouteChildren)

interface ReportsRouteChildren {
  ReportsSalesRoute: typeof ReportsSalesRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsSalesRoute: ReportsSalesRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface TeamRouteChildren {
  TeamWelcomeRoute: typeof TeamWelcomeRoute
  TeamJoinTokenRoute: typeof TeamJoinTokenRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamWelcomeRoute: TeamWelcomeRoute,
  TeamJoinTokenRoute: TeamJoinTokenRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  BookingSettingsRoute: BookingSettingsRoute,
  BookingsRoute: BookingsRoute,
  BusinessProfileRoute: BusinessProfileRoute,
  BusinessTypeRoute: BusinessTypeRoute,
  ClientsCompareRoute: ClientsCompareRoute,
  CommissionsRoute: CommissionsRoute,
  CustomersRoute: CustomersRoute,
  DataDeletionRoute: DataDeletionRoute,
  DeliverySettingsRoute: DeliverySettingsRoute,
  DevicesRoute: DevicesRoute,
  DineInRoute: DineInRoute,
  DocumentsRoute: DocumentsRoute,
  ForgotPasswordRoute: ForgotPasswordRouteWithChildren,
  ImportOrdersRoute: ImportOrdersRoute,
  IngredientsRoute: IngredientsRoute,
  InventoryRoute: InventoryRouteWithChildren,
  LanguageRoute: LanguageRoute,
  LegalRoute: LegalRoute,
  ListingsRoute: ListingsRoute,
  LoanCalculatorRoute: LoanCalculatorRoute,
  MoreRoute: MoreRoute,
  NewBookingRoute: NewBookingRoute,
  NewOrderRoute: NewOrderRoute,
  NotificationSettingsRoute: NotificationSettingsRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  OrderFormRoute: OrderFormRoute,
  OrdersRoute: OrdersRouteWithChildren,
  PaymentDetailsRoute: PaymentDetailsRoute,
  PaymentSetupRoute: PaymentSetupRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  PipelineOverviewRoute: PipelineOverviewRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  ProfitRoute: ProfitRoute,
  PurchaseOrdersRoute: PurchaseOrdersRoute,
  RecipesRoute: RecipesRoute,
  RenewalsRoute: RenewalsRoute,
  ReportsRoute: ReportsRouteWithChildren,
  RequirementsRoute: RequirementsRoute,
  SearchRoute: SearchRoute,
  ServicesRoute: ServicesRoute,
  ServicesSummaryRoute: ServicesSummaryRoute,
  SplashRoute: SplashRoute,
  StockRoute: StockRoute,
  StockTakeRoute: StockTakeRoute,
  SuppliersRoute: SuppliersRoute,
  TablesRoute: TablesRoute,
  TeamRoute: TeamRouteWithChildren,
  TermsRoute: TermsRoute,
  UniversityInsightsRoute: UniversityInsightsRoute,
  ViewingsRoute: ViewingsRoute,
  WhatsappTemplatesRoute: WhatsappTemplatesRoute,
  BookCodeRoute: BookCodeRoute,
  CommissionIdRoute: CommissionIdRoute,
  ConnectedPlatformsPlatformRoute: ConnectedPlatformsPlatformRoute,
  CustomerCustomerIdRoute: CustomerCustomerIdRoute,
  DineTableIdRoute: DineTableIdRoute,
  DocumentIdRoute: DocumentIdRoute,
  ListingIdRoute: ListingIdRoute,
  OrderCodeRoute: OrderCodeRoute,
  PurchaseOrdersIdRoute: PurchaseOrdersIdRoute,
  RenewalIdRoute: RenewalIdRoute,
  RequirementIdRoute: RequirementIdRoute,
  StockTakeIdRoute: StockTakeIdRoute,
  TrackOrderRefRoute: TrackOrderRefRoute,
  ViewingIdRoute: ViewingIdRoute,
  ApiPublicAdminRoute: ApiPublicAdminRoute,
  ApiPublicDeliveryQuoteRoute: ApiPublicDeliveryQuoteRoute,
  ApiPublicOrderFormRoute: ApiPublicOrderFormRoute,
  ApiPublicTrackingRoute: ApiPublicTrackingRoute,
  ApiPublicStripeActivateRoute: ApiPublicStripeActivateRoute,
  ApiPublicStripeCheckoutRoute: ApiPublicStripeCheckoutRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicWebhooksTiktokRoute: ApiPublicWebhooksTiktokRoute,
  ApiPublicOauthTiktokCallbackRoute: ApiPublicOauthTiktokCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
